[build]
  command = "ng build --configuration=production"
  publish = "dist/aleksander-nikolli-portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/angular-runtime"
