    [build]
      command = "ng build --configuration=production"
      publish = "dist/aleksander-nikolli-portfolio/browser"
      plugins = [
        { package = "@netlify/angular-runtime", disable = true }
      ]
    