
[build]
  command = "npm run build"
  publish = "dist/aleksander-nikolli-portfolio/browser/it"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/chi-sono"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/contatti"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/servizi"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/progetti"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/progetti/*"
  to = "/index.html"
  status = 200

# Reindirizza tutto ciò che inizia con /en verso la build inglese
[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200
