[build]
  publish = "dist/aleksander-nikolli-portfolio/browser"
  command = "ng build --configuration=production --localize"

# Italiano come lingua di default
[[redirects]]
  from = "/"
  to = "/it/index.html"
  status = 200

# Italian routes
[[redirects]]
  from = "/it/*"
  to = "/it/index.html"
  status = 200

[[redirects]]
  from = "/it"
  to = "/it/index.html"
  status = 200

# English routes
[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200
