services:
  - type: web
    name: angular-ssr-frontend
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install && npm run build:ssr
    startCommand: node dist/aleksander-nikolli-portfolio/server/main.js
    rootDir: .
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
